### ISSUE TITLE
Par. 3.1 Remarks

### ISSUE THREAD

**Issue by janbaltussen** [thosgood/qubit.guide#11]
1. Text Fig.3.2: "....photon enters input | i >": wouldn't it be better to use j (conform B_ij)?
2. "...This is summarised in Fig. 3.3....": doesn't this figure fit the quantum situation, discussed in the following?

**Comment by thosgood** [comment]
1. This is a nice point, I'll change this!
2. I'm not too sure what you mean here: this diagram is meant to be showing what you might expect to happen classically (but which doesn't happen in reality). I will change "probability amplitude" to "probability" to maybe make this a bit clearer. Does that address your issue with it?

**Comment by janbaltussen** [comment]
2. Sorry. I downloaded a pdf-version, and fig.3.3 had i/sqrt(2) as a
probability amplitude. The on-line version has the correct 1/sqrt(2).

I like the book, but I should be reading it on-line....

Kind regards, Jan Baltussen

Op ma 19 sep. 2022 om 15:59 schreef Tim Hosgood ***@***.***>:

**Comment by thosgood** [comment]
ah ok, if you download the PDF version again then it should have all the latest updates! putting a "last updated" 
date on the generated PDF is on my to-do list :-) but thanks again for your feedback!
