### ISSUE TITLE
A few typo's - chapter 4

### ISSUE THREAD

**Issue by janbaltussen** [thosgood/qubit.guide#14]
4.1 Footnote 76
...and it is a very convenient fact that any finite dimensional inner product spaces is automatically a Hilbert space...
Spaces -> space?

4.6
Conversely say that... 
$A \ket{e_k}=\alpha_k$
Should be
$A \ket{e_k}=\alpha_k \ket{e_k}$

The same for:
$B \ket{e_k}=\beta_k$
Should be
$B \ket{e_k}=\beta_k \ket{e_k}$

This says that there does not exist any state for which $σ_Aσ_B$ is less THAT some specific value,
Should be: ... less THAN...

**Comment by thosgood** [comment]
thanks, fixed!
