### ISSUE TITLE
Confused by figure 2.1 and Subsequent math

### ISSUE THREAD

**Issue by prakity** [thosgood/qubit.guide#19]
![2 1 Composing quantum operations  Introduction to Quantum Information Science](https://user-images.githubusercontent.com/1106259/222986685-1ef1aea8-52ef-4c09-ae30-e8ad0906942d.png)

looking at the math below the figure 2.1 for |k>. Expanding math

|0> = U00 |0> + U10 |1>
and
|1> = U01 |0> + U11 |1>

looking at figure 2.1 I think it’s 
|0> = U00 |0> + U01 |1>
and
|1> = U10 |0> + U11 |1>

didn’t check 2nd equation.  If my comment is correct it text would be cleared to also include sum expansion

philip

**Comment by thosgood** [comment]
I think there's maybe some confusion about what these sums are meant to represent, so I'll write a sentence or two about this. The idea is that $|0\rangle$ will evolve into $|0\rangle$ with probability $U_{00}$, and into $|1\rangle$ with probability $U_{10}$. So how can we describe the final situation if we know that we started with $|0\rangle$? Well, we have a superposition of these two possible results, namely $U_{00}|0\rangle+U_{10}|1\rangle$.
