### ISSUE TITLE
Latex issue in 2.6

### ISSUE THREAD

**Issue by GBisi** [thosgood/qubit.guide#38]
In the first red box of 2.6, the title, which contains some Latex code is not correctly printed as it remains as 

"The groups $\mathrm{SU}(2)$ and $\mathrm{SO}(3)$"

I checked the source but I was not able to find the reason why it is not properly displayed

**Comment by thosgood** [comment]
That's some small KaTeX rendering bug, but it's an easy fix. I'll fix it in the next big update. Thanks for pointing it out!
